# config_place.yaml
user_inputs:
  center: 52.373095,4.8931012
  radius: 1000

map_settings:
  draw:
    buildings: true
    landuse_green: true
    water: true
    rail: true
    road_edges: true

  colors:
    background: "#FFFFFF"
    buildings_fill: "#E6E6E6"
    buildings_outline: "#7A7A7A"
    water: "#D9D9D9"
    rail: "#BEBEBE"
    motorway: "#2B2B2B"
    trunk: "#2B2B2B"

    primary: "#2B2B2B"
    secondary: "#3A3A3A"
    tertiary: "#4A4A4A"
    residential: "#5A5A5A"
    service: "#6A6A6A"

    footway: "#7A7A7A"
    other: "#808080"

  widths:
    motorway: 2.2
    trunk: 2.0
    primary: 1.9
    secondary: 1.6
    tertiary: 1.3
    residential: 2.0
    service: 0.8
    footway: 0.6
    other: 0.9

  figure:
    width_in: 21
    height_in: 12
    dpi: 300
    margin_frac: 0.02

  output:
    out: "./src/images/poster.png"
    svg: true
    no_axes: true
    show: false
    title: "Amsterdam"
    # coords: "50.900°N, 5.963°E"
    coords_auto: dms
    font: null         # e.g. "Inter"
    icon: "./src/icons/home.png"
    seed: 42